# Generated by Django 4.2.3 on 2023-07-09 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="facility_uid",
            field=models.CharField(max_length=12, null=True),
        ),
    ]
