# Generated by Django 4.2.3 on 2023-07-10 03:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_availability_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="calories",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="min_heart_rate",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="which_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
