# Generated by Django 4.2.3 on 2023-07-10 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_notification_calories_notification_min_heart_rate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="max_heart_rate",
            field=models.FloatField(null=True),
        ),
    ]
