# Generated by Django 4.2.3 on 2023-07-10 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_notification_max_heart_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="end_time",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="start_time",
            field=models.CharField(max_length=30, null=True),
        ),
    ]
