# Generated by Django 4.2.3 on 2023-07-10 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_notification_end_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="avg_heart_rate",
            field=models.FloatField(null=True),
        ),
    ]
