# Generated by Django 4.2.3 on 2023-07-10 04:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_notification_avg_heart_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="paramedic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="paramedic",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
