# Generated by Django 4.2.3 on 2023-07-10 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_emergency"),
    ]

    operations = [
        migrations.AddField(
            model_name="emergency",
            name="message",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="message",
                to="accounts.notification",
            ),
        ),
    ]
