# Generated by Django 4.2.3 on 2023-07-10 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_emergency_message"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emergency",
            name="notification",
        ),
    ]
