# Generated by Django 4.2.3 on 2023-07-10 06:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_remove_emergency_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="emergency",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2023, 7, 10, 6, 4, 51, 38550, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
    ]
