# Generated by Django 4.2.3 on 2023-07-10 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_emergency_date_created"),
    ]

    operations = [
        migrations.CreateModel(
            name="Emergencys",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("messages", models.CharField(max_length=50)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message",
                        to="accounts.notification",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Emergency",
        ),
    ]
