# Generated by Django 4.2.3 on 2023-07-16 04:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_emergency_delete_emergencys"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notifications",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.CharField(max_length=30, null=True)),
                ("end_time", models.CharField(max_length=30, null=True)),
                ("max_heart_rate", models.FloatField(null=True)),
                ("min_heart_rate", models.FloatField(null=True)),
                ("avg_heart_rate", models.FloatField(null=True)),
                ("calories", models.FloatField(null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "paramedic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="paramedics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notified_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
