# Generated by Django 4.2.3 on 2023-07-16 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_notifications"),
    ]

    operations = [
        migrations.AddField(
            model_name="emergency",
            name="doc_message",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="emergency",
            name="notification",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.notifications",
            ),
        ),
    ]
