# Generated by Django 4.2.3 on 2023-07-16 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_emergency_doc_message_alter_emergency_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="emergency",
            name="issue",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
