# Generated by Django 4.2.3 on 2023-07-16 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0018_emergency_issue"),
    ]

    operations = [
        migrations.AddField(
            model_name="emergency",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "pending"),
                    ("accepted", "accepted"),
                    ("rejected", "rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="health_status",
            field=models.CharField(
                choices=[
                    ("unknown", "unknown"),
                    ("stable", "stable"),
                    ("critical", "critical"),
                ],
                default="unknown",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="smartwatch_serialno",
            field=models.CharField(max_length=12, null=True),
        ),
    ]
