# Generated by Django 4.2.3 on 2023-07-17 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0019_emergency_status_user_health_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="emergency",
            name="paramedic",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assigned_paramedic",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
